# Generated by Django 2.2.3 on 2019-10-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
    ]
